[workspace]
members = ["phf", "phf_builder", "phf_codegen", "phf_codegen/test", "phf_generator", "phf_macros", "phf_shared"]

[patch.crates-io]
unicase = { git = 'https://github.com/Bobo1239/unicase.git' }
